name: CI

on:
  push:
    branches:
      - main
  pull_request:
env:
  CI: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get turbo cache directory
        uses: actions/cache@v2
        with:
          path: |
            .turbo
            **/*/.turbo
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ github.action }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      fail-fast: true
      matrix:
        node-version: [14]
        os: [ubuntu-latest]
        include:
          - node-version: 16
            os: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Get turbo cache directory
        uses: actions/cache@v2
        with:
          path: |
            .turbo
            **/.turbo
          key: ${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/pnpm-lock.json') }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test


